### ISSUE TITLE
Add stable tag

### ISSUE THREAD

**Issue by benatespina** [froala/KMSFroalaEditorBundle#11]
Hi, this package hasn't enabled auto-update inside Packagist so, the last merged PR is not referenced yet. Can you update the reference and by the way, can you tag a stable version?

Thanks in advance.

**Comment by samarhxc** [comment]
I added a v3.0.0 tag on master branch, have i to add something (branch-alias or something else) to composer.json ?

**Comment by stefanneculai** [comment]
@samarhxc I noticed that you tagged couple of minutes ago the Symfony plugin to V3.0.0. Would it be possible to delete that tag and instead keep it in sync with the editor? This way it would be easier for us to know which plugins are up to date and which not. Here is how we do it for the other plugins:

- V2.1.0 -> same with editor
	- **V2.1.0_1 (this would be the right one now)** -> V2.1.0 of the editor but new update for the symfony plugin.
	- V2.1.0_2 -> V2.1.0 of the editor but new update for the symfony plugin.
- V2.1.1 -> same with editor

Thanks.

**Comment by benatespina** [comment]
@samarhxc  yeah! After that, you have to update your package in this url to sync your new tag with packagist https://packagist.org/packages/kms/froala-editor-bundle

**Comment by benatespina** [comment]
@samarhxc Thanks!! Now your bundle works like a charm ;)

**Comment by samarhxc** [comment]
No problem, from now the bundle version will be sync with the Froala editor version.
I think i have to add this to composer.json :

``
{
    "extra": {
        "branch-alias": {
            "dev-master": "2.1.x-dev"
        }
    }
}
``

This is correct or i missed something ?

**Comment by benatespina** [comment]
@samarhxc This is correct, is a simple alias to master branch, anyway it's not mandatory but it's a good practice.

**Comment by samarhxc** [comment]
Ok, 
thank you for your help.
