### ISSUE TITLE
Alert is seen after image or video uplaod and click outside

### ISSUE THREAD

**Issue by GovardhanCel** [froala/KMSFroalaEditorBundle#110]
**Description**
Alert is seen after image or video uplaod and click outside.

**Expected behavior.**
After image uplaod and click outside, browser should not display any alerts.

**Actual behavior.**
Alert is seen after image or video uplaod and click outside.

**Editor version.**
Latest

**Additional resources**
![Plugins-Symfony-FROALA](https://user-images.githubusercontent.com/43410193/72963382-2c636680-3ddd-11ea-900d-9d5bc4cf05e2.gif)

**Related issue**
https://github.com/froala-labs/froala-editor-js-2/issues/1896

**Comment by sguionni** [comment]
This is the auto save option.
Try to disable it or configure the URL.
