### ISSUE TITLE
How to work with Froala inside a form with multiple fields ?

### ISSUE THREAD

**Issue by AxelBriche** [froala/KMSFroalaEditorBundle#115]
Froala autosave don't push all my other fields in the ajax query.

```
class ThreadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('messages', CollectionType::class, [
                'entry_type' => MessageType::class,
                'entry_options' => [
                    'label' => false
                ],
            ])
            ->add('visible')
            ->add('locked')
            ->add('pinned')
            ->add('send', SubmitType::class, [
                'label' => 'Envoyer',
            ])
        ;
    }
    ...
}
class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('content', FroalaEditorType::class,[
            'saveURL' => 'thread_create',
            'language' => 'fr',
            'placeholderText' => 'Tapez votre message ici',
            'toolbarInline' => false,
            'attribution' => false,
            'label' => false,
            'pastePlain' => true
        ]);
    }
    ...
}
```

<img width="1083" alt="Capture d’écran 2020-06-05 à 11 35 01" src="https://user-images.githubusercontent.com/1295251/83861289-aeb34e00-a720-11ea-92f7-490da7c8c0f0.png">

<img width="352" alt="Capture d’écran 2020-06-05 à 11 27 44" src="https://user-images.githubusercontent.com/1295251/83860473-95f66880-a71f-11ea-988b-cb92f3ca18f9.png">

<img width="364" alt="Capture d’écran 2020-06-05 à 11 27 26" src="https://user-images.githubusercontent.com/1295251/83860433-8bd46a00-a71f-11ea-84d7-bbeacbaf1d7a.png">

And inside the query, my "content" field is named "body".

What is the right way to work with froala inside a form with multiple fields please?
Thanks.

**Comment by AxelBriche** [comment]
The solution is inside the official doc here but doen't work with this bundle:
https://froala.com/wysiwyg-editor/docs/concepts/save/inside-form/

**Comment by jmsche** [comment]
You are looking at the wrong part of docs, here they are for autosave: https://froala.com/wysiwyg-editor/docs/concepts/save/autosave/

Not sure why you would expect to receive all fields as the docs state you will get the content of the textarea.

Maybe the `saveParams` is something you could play with to get other fields.
