### ISSUE TITLE
Error 1 image cannot be loaded on Froala Symfony 4.x

### ISSUE THREAD

**Issue by gabrielncl** [froala/KMSFroalaEditorBundle#122]
Hello, I'm working with Symfony 4.x without flex and last version of froala, and I get `Error 1: Image cannot be loaded from the passed link.`

My config of froala editor : 
`kms_froala_editor:
  language: "fr"
  pluginsDisabled: ["save"]
  imageMaxSize: 2097152
  imageUploadFolder: "/uploads"
  imageUploadPath: "/uploads"
  publicDir: "/web"`

My Image is being saved in the folder but it can be retrieved by the editor.

**Comment by jmsche** [comment]
Hi, what version of the bundle are you using? Are you sure about your configuration?

**Comment by gabrielncl** [comment]
Hi, it's the dev-master I think it's the 4.0.0, yes my configuration is working the path is the good one

**Comment by gabrielncl** [comment]
<img width="296" alt="Capture d’écran 2021-01-26 à 11 24 30" src="https://user-images.githubusercontent.com/44476244/105833129-10cf0500-5fc9-11eb-9c8d-19a0562b4a98.png">

**Comment by jmsche** [comment]
Can you check logs & xhr response to see what fails?

**Comment by gabrielncl** [comment]
Now it's working, I cleaned cached files and it seems to work

**Comment by jmsche** [comment]
Could you please close the issue? :)
