### ISSUE TITLE
Weird bug with toolbarInline enabled on Firefox

### ISSUE THREAD

**Issue by dimitribocquet** [froala/KMSFroalaEditorBundle#13]
I found a weird bug only viewable on Firefox. The toolbar is loaded only with basic options (bold, italic, font). BUT, when i open the "Web Developper" menu, the full toolbar appears.

This bug is only on Firefox.

I don't know if this bug is directly in Froala, or in this Bundle (or only with me).

**Comment by samarhxc** [comment]
@stefanneculai can you take a look ?

**Comment by samarhxc** [comment]
Fixed.
