### ISSUE TITLE
Notice: Undefined index: basePath in /vendor/kms/froala-editor-bundle/Service/OptionManager.php line 68

### ISSUE THREAD

**Issue by cassianotartari** [froala/KMSFroalaEditorBundle#14]
Hi! I've followed all the steps described in readme but when I try to use the form type it throws:
```
Notice: Undefined index: basePath in /vendor/kms/froala-editor-bundle/Service/OptionManager.php line 68
```

I've already defined a ``basePath`` in config but didn't worked.

**Comment by samarhxc** [comment]
Hi, 
can you show me your config file please ?

**Comment by cassianotartari** [comment]
```yaml
kms_froala_editor:
    language: "%locale%"
    includeJQuery: false
    basePath: "/my/custom/path"
```

I was looking the code before and I think is something related to Symfony version, I'm using 2.3. It wasn't setting defaults inside form type. I've already deleted all the stuff but I've tried to change some method to set defaults and the error changed to other place. I'm working with ckeditor but it has dependencies with others bundle and I can't update it to newest version. The reason that I'm looking to other WYSIWYG editor is for work in mobile

**Comment by samarhxc** [comment]
You have to remove the basePath in your config file, clean the cache and it should works.

**Comment by balvirsingh** [comment]
Hi,
I removed the basePath in your config file and clean the cache but again same problem.

**Comment by samarhxc** [comment]
Can you show me your actual configuration file and your code that create the form please ?

**Comment by Khaldoun488** [comment]
same problem with me

**Comment by Khaldoun488** [comment]
I just updated to Symfony 2.8.6 and it works.

**Comment by AnthonyPavaux** [comment]
I must remain a version 2.6 sf2 with dependence . he has no other solution than a past version > 2.8?

**Comment by samarhxc** [comment]
I will update the bundle next week to the last Froala version. Do you have an idea about problem with sf <2.8 ?

**Comment by samarhxc** [comment]
This issue is fixed ?
