### ISSUE TITLE
Configuration for Symfony 3.0.6 

### ISSUE THREAD

**Issue by prakashsinghgaur** [froala/KMSFroalaEditorBundle#16]
I have installed and configured it as given in the instructions, but while adding it to the form as given below, it says Could not load type "froala"

$builder->add( "yourField", "froala" );

Can you specifically tell how to add it in form in Symfony 3, because Symfony 3 requires Type and Class to be included and declared, explicitly like below mentioned example:-

Type:-
use Symfony\Component\Form\Extension\Core\Type\TextType; 

and Class-
builder->add('title', TextType::class)

Do we include it from any namespace, as above?
Thanks..

**Comment by samarhxc** [comment]
You have to use : 

use KMS\FroalaEditorBundle\Form\Type\FroalaEditorType;

and insert the editor like that :

->add( 'yourField', FroalaEditorType::class)

**Comment by prakashsinghgaur** [comment]
Thanks for the reply.

But after doing this a new runtime error occurred:-

Key "language" for array with keys "fileUploadURL, imageManagerDeleteURL, imageManagerLoadURL, imageUploadURL, imageUploadParams, imageManagerLoadParams, imageManagerDeleteParams, fileUploadParams" does not exist in KMSFroalaEditorBundle:Form:froala_widget.html.twig at line 21

Any help on this!

**Comment by benbender** [comment]
Same applies for 2.8.6 (current) with the master-branch of the bundle.

**Comment by samarhxc** [comment]
The option "language" has to be defined in your config file or in your form declaration.
I need to add a test or set a default language.

"en_us" does not exist, look at the public/froala/js/languages/ folder.

**Comment by prakashsinghgaur** [comment]
I tried with en_ca as language in config.yml but still no luck
The editor is not showing up

**Comment by samarhxc** [comment]
Can you copy paste your config file, your form declaration, and the error please ?

**Comment by prakashsinghgaur** [comment]
My config.yml is as follows:-

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

kms_froala_editor:

    # The Froala editor path.
    # Default: the editor version included in the bundle.
    basePath: "/bundles/kmsfroalaeditor/"
    language: en_ca
 

Form Declaration:

class VisionType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
	$builder
		->add('title', FroalaEditorType::class)
        ->add('save', SubmitType::class, array('label' =>'Submit',  'attr'=>array('class'=>'btn btn-primary', 'style' =>'margin-bottom:15px')));
	}
}

There is no error.. just Editor does not appear.

Thanks

**Comment by samarhxc** [comment]
You can delete the basePath in you config file if you are using the version of froala provided with the bundle.

**Comment by samarhxc** [comment]
This issue is fixed ?

**Comment by AngeloAvv** [comment]
I guess no, I'm having the same problem as mentioned by @prakashsinghgaur 
Editor not showing up

**Comment by EricGrivilers** [comment]
Maybe the related assets are not installed.
`php bin/console assets:install`

**Comment by lasanthaa** [comment]
I did step 1,2,3,4,5.But i do not know how to continue with step 6.Can someone help me?Is there any complete code for the form?

**Comment by nicola-de-smet** [comment]
I've got the same issue ! I followed the insctructions but the editor not showing up only a textarea. Did you find a solution @AngeloAvv, @prakashsinghgaur, @sguionni

**Comment by sguionni** [comment]
Can you copy/paste your configuration ?
Do you have any error in your console ?

**Comment by nicola-de-smet** [comment]
I don't have much time this week. I will try to do it next week !

**Comment by AngeloAvv** [comment]
I'm sorry @nicola-de-smet but I no longer use Symfony. As far as I can remember, I migrated to another editor since I didn't received any further intel on how to let it work.
