### ISSUE TITLE
Icon plugin d'ont show

### ISSUE THREAD

**Issue by fyher** [froala/KMSFroalaEditorBundle#20]
i have 2.3 version and the icon for the plugin code view it's not in the toolbar , i have the see de css and js file .

**Comment by samarhxc** [comment]
If you update to dev-master branch it's normally fixed.

**Comment by fyher** [comment]
it's a 2.3.3 ?

**Comment by fyher** [comment]
it's good , i have remove and reinstall it :)

**Comment by samarhxc** [comment]
The bug is fixed on master branch but not tagged for the moment, it'll be at next Froala update :)
