### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by xpersonas** [froala/KMSFroalaEditorBundle#21]
It doesn't seem that the theme setting is used appropriately. I'm setting this in the config.yml...

theme: 'gray'

However, no theme changes appear. And no missing css or anything is reported in the console. So I'm thinking that theme key is not being used?

If I add the theme css to the froala_widget.html.twig then it shows just fine.

<link rel="stylesheet" type="text/css" href="{{ asset( basePath ~ 'css/themes/gray.min.css' ) }}" />

Am I trying to set the theme incorrectly or was it maybe forgotten?

**Comment by samarhxc** [comment]
I forgot to include the correct theme CSS, just fixed.
