### ISSUE TITLE
font-awsome.min.css over http

### ISSUE THREAD

**Issue by mpaden3** [froala/KMSFroalaEditorBundle#23]
There is a problem with loading this css file. If your server doesn't allow http connections (just https), it wont be loaded. For some reason, only this file is loaded over http (unlike codemirror.min.css which is loaded over https.

I solved the problem adding by https link to this css file in my <head> element, but it should still be fixed in the framework itself.

**Comment by samarhxc** [comment]
You're right, just fixed in last commit.
