### ISSUE TITLE
quickInsertButtons config option missing

### ISSUE THREAD

**Issue by treetop1500** [froala/KMSFroalaEditorBundle#27]
This option appears to be missing from the config for your bundle. When trying to define this parameter in the config, it will throw an invalidConfigurationException:

```
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "quickInsertButtons" under "kms_froala_editor"
```

https://www.froala.com/wysiwyg-editor/docs/options#quickInsertButtons

**Comment by samarhxc** [comment]
Just added in the last commit.
