### ISSUE TITLE
Using KMSFroala with BeSimple/i18n bundle

### ISSUE THREAD

**Issue by nassuf** [froala/KMSFroalaEditorBundle#28]
Hello,

When I am using Froala with i18n bundle I have this error:

> Catchable Fatal Error: Argument 1 passed to KMS\FroalaEditorBundle\Service\OptionManager::__construct() must be an instance of Symfony\Component\Routing\Router, instance of BeSimple\I18nRoutingBundle\Routing\Router given

That is because your OptionManager service expect a Symfony Router object in the constructor. Is it possible to change it to expect a RouterInterface so it will match the cases where people use tierce Router ?

Would then be:
> public function __construct( RouterInterface $p_router )

Instead of:
> public function __construct( Router $p_router )

Thanks

**Comment by samarhxc** [comment]
Fixed: #34
