### ISSUE TITLE
Can be used this bundle as a WYSIWYG for Twig Templates?

### ISSUE THREAD

**Issue by reypm** [froala/KMSFroalaEditorBundle#29]
I will start developing a functionality for the application I am working on and I need to give the users the ability to edit templates (.html.twig files) on the fly. Think for example in a few email templates where the users would like to add some images, text, copyright and also dynamic content. Can this be done with this bundle? Can I take a template and let the user edit it and save it afterwards?

**Comment by samarhxc** [comment]
Hello, 
sorry for late reponse.
Edited content is converted into HTML so i think you will not be able to edit TWIG file.
