### ISSUE TITLE
Make bundle compatible with symfony 2.6

### ISSUE THREAD

**Issue by Intrepidity** [froala/KMSFroalaEditorBundle#3]
The bundle requires a version of symfony lower than 2.6.

Does anything need to happen to make it compatible or can you just bump the requirement in composer.json?

**Comment by stefanneculai** [comment]
@samarhxc any thoughts on this one?

**Comment by Intrepidity** [comment]
I quickly reviewed the symfony 2.5 to 2.6 upgrade documentation and I don't think there's any relevant BC breaks there. I think it's a matter of bumping it in the develop branch and just trying it out..

**Comment by stefanneculai** [comment]
I believe that too. @samarhxc has created this bundle and he should be more familiar. If you could give it a try that would be great.

**Comment by samarhxc** [comment]
I updated the composer.json requirement (i don't really know what to set but the bundle is working for me with the last symfony release).

**Comment by Intrepidity** [comment]
Thanks, we're testing it on our side right now. I'll get back to you on the results next week as I'm AFK the coming days. :)

**Comment by Intrepidity** [comment]
Perfect, works like a charm :) Consider this issue closed :+1:

**Comment by samarhxc** [comment]
Nice, take a look to the documentation, i comitted some updates ;)
