### ISSUE TITLE
Avairy Key integration failed.

### ISSUE THREAD

**Issue by lasanthaa** [froala/KMSFroalaEditorBundle#31]
Hi.
My i cannot integrate advanced edit into editor.I added my aviary api key and the script tag into this file in symfony: **symfony/KMSFroalaEditorBundle/blob/master/Resources/views/Form/froala_widget.html.twig.**
Script tag is
**<script type="text/javascript" src="{{ asset( basePath ~ 'js/third_party/image_aviary.min.js' ) }}"></script>**
I added button "aviary" to the editor also.
'imageReplace', 'imageAlign', 'imageRemove', '|', 'imageLink', 'linkOpen', 'linkEdit', 'linkRemove', '-', 'imageDisplay', 'imageStyle', 'imageAlt', 'imageSize','aviary']

I got the aviary api key from https://console.adobe.io/  for development.(I did not send it for approve.)
Why this aviary integration does not work?
I am glad if anyone can help.
Thanks

**Comment by samarhxc** [comment]
Hello,
the Avairy integration will come in the next update (maybe tonight or next week).

**Comment by samarhxc** [comment]
Hello,
I just pushed the enhancement.
Feel free to reopen if it's not ok.
