### ISSUE TITLE
Plugins Issues

### ISSUE THREAD

**Issue by matbuis** [froala/KMSFroalaEditorBundle#32]
Hi !

Great work for the plugin, works like a charm.
I still got a problem, i found the way to display buttons in my toolbar but i can't use it. I mean when i click on the "colors" button for example, nothing's happening. I included all the js and css files following the good practices, but it still doesn't work.

I'm working with Symfony 3.2.9. I have to let it go for few days because i got other missions, but if anyone could help me it would be really kind =)

Mathieu.

**Comment by samarhxc** [comment]
Hello Mathieu, 
do you have any error in your browser's console ?
What kind of buttons is it ?

**Comment by matbuis** [comment]
Hi. 

I got no errors in console nor browser.
I displayed the buttons on the toolbar but when i click on the plugins buttons it doesnt work, nothing happens. The default toolbar buttons (bold, italic, underline...) work fine, but i need to use some plugins like "colors".

Thanks for the help i know it's not a lot of informations but i got no console message to share, that's why im here =)

**Comment by matbuis** [comment]
Hi there !

I was away from my project for few weeks. Now i can give you the exact includes i made to use your editor.

Here are the scripts i want to use (pretty simple) :

`<script src="{{ asset('bundles/kmsfroalaeditor/froala_editor_2.5.1/js/froala_editor.min.js') }}"></script>
    <script src="{{ asset('bundles/kmsfroalaeditor/froala_editor_2.5.1/js/languages/fr.js') }}"></script>
    <script src="{{ asset('bundles/kmsfroalaeditor/froala_editor_2.5.1/js/plugins/image.min.js') }}"></script>
    <script src="{{ asset('bundles/kmsfroalaeditor/froala_editor_2.5.1/js/plugins/image_manager.min.js') }}"></script>
    
    <script src="{{ asset('bundles/kmsfroalaeditor/froala_editor_2.5.1/js/plugins/align.min.js') }}"></script>`
