### ISSUE TITLE
Is there any way to change editor width and height in runtime?

### ISSUE THREAD

**Issue by lasanthaa** [froala/KMSFroalaEditorBundle#33]
Hi..
Is there any way to change editor width and height runtime?
It is possible if we can send data from controller to config.yml or controller to froala_widget.html.twig.

Thanks

**Comment by samarhxc** [comment]
Yes, 
Froala has height and width properties : [https://www.froala.com/wysiwyg-editor/docs/options#height](https://www.froala.com/wysiwyg-editor/docs/options#height).

You can define these parameters in your config.yml file or in your form builder.

**Comment by lasanthaa** [comment]
Hi..
But i think when i define width and height in config.yml it will be static.
eg-:
kms_froala_editor:
      height: 300
      width:300

How can i define it in formBuilder?

 $entity = new Example();
 $form= $this->createFormBuilder($entity)
                    ->add('Sticker',FroalaEditorType::class,array(
                         'required'   => true,
                           'width'     => 576,
                           'height'  =>192))
                    ->add('submit', SubmitType::class, array('label' => 'Save'))
                    ->getForm();
Can i make it adding width and height as above?
Thank you

**Comment by samarhxc** [comment]
Yes, 
all options can be overriden in the form builder : [https://github.com/froala/KMSFroalaEditorBundle#step-6--add-froala-to-your-form](https://github.com/froala/KMSFroalaEditorBundle#step-6--add-froala-to-your-form)

**Comment by lasanthaa** [comment]
Hi..
**But it is not working for me** 

This is my full builder class ExampleType
![image](https://user-images.githubusercontent.com/12367805/27542109-dcf5033e-5aa3-11e7-96e1-81787371eb6c.png)

This my controller function.
![image](https://user-images.githubusercontent.com/12367805/27542161-08df7e98-5aa4-11e7-90cf-42a8535b1abf.png)

**Comment by samarhxc** [comment]
Not sure if it's important but width and height are numbers, not string.
