### ISSUE TITLE
Language has to be configured

### ISSUE THREAD

**Issue by UFTimmy** [froala/KMSFroalaEditorBundle#34]
Howdy,

The readme says "Step 5 : Configure the bundle (optional)", but this step is not really optional. Language is required, as seen here:

https://github.com/froala/KMSFroalaEditorBundle/issues/16#issuecomment-219664626

So I think the docs should give the minimum required configuration in one section, and then another section about optional configuration.

If you agree, I don't mind updating them.

Thanks!

**Comment by samarhxc** [comment]
Yes you're right, i changed the documentation.
Thx!
