### ISSUE TITLE
can't change language

### ISSUE THREAD

**Issue by marvin-SL** [froala/KMSFroalaEditorBundle#37]
hello, 

I can't switch language. It stays to default language. Here's my config.yml : 
```
kms_froala_editor:
    language: 'es'
```
my forms : 
```
...
        ->add("content", FroalaEditorType::class, [
                    "language" => "es",
        ])
```
I've tried to clear cache, it 's still in english 
Can you help me ?

Symfony 3.3.4

**Comment by stefanneculai** [comment]
@marvin-SL I believe somehow the language file is not included. Do you have a page where we can check? Thanks.
