### ISSUE TITLE
FroalaEditor doesn't show anything

### ISSUE THREAD

**Issue by chhoulet** [froala/KMSFroalaEditorBundle#38]
May I did a mistake in my config ? 
I follow all the steps, but nothing appears. Here my config:

config.yml:
`kms_froala_editor:
    language: "fr"
`

My ArticleType.php:
use KMS\FroalaEditorBundle\Form\Type\FroalaEditorType;

class ArticleType extends AbstractType
{   
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class, array('label'=>'Titre',
                                                      'required'=>false,
                                                      'attr'=>['class'=>'form-control']))
                     ->add('main', FroalaEditorType::class, array('label'=>'Texte'))
                     ->add('Validez', SubmitType::class)
    }

I added these links in my layout:
<link href="{{ asset('bundles/framework/css/froala_style.min.css') }}" rel="stylesheet" type="text/css" /> in the header and 
<script src="{{ asset('bundles/framework/js/froala_editor.pkgd.min.js') }}"></script> in my js_block

All the assets are installed in the vendor and in the web bundles. 

Any idea please ? Thanks for your help.

**Comment by samarhxc** [comment]
Hello, 
do you have something in the console ?

**Comment by chhoulet** [comment]
Hello,

Thanks for your help. That's what I get in the console (error message in red color): 
GET http://localhost/alecHabitat1/web/bundles/kmsfroalaeditor/froala_editor_2.7.1/js/third_party/sp...

Here the header of th response 

Cache-Controlno-cache, privateConnectionKeep-AliveContent-Length471Content-Security-Policyblock-all-mixed-content; font-src 'self' 'unsafe-inline' https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800 https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic https://use.fontawesome.com/4310d05301.js; img-src 'self' facebook.com flickr.com; script-src 'self' 'unsafe-inline' https://code.jquery.com/jquery-1.12.4.js https://code.jquery.com/ui/1.12.1/jquery-ui.js https://use.fontawesome.com/4310d05301.js https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js; style-src 'self' 'unsafe-inline' https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css https://resources/demos/style.css //netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css //netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css; report-uri router.request_context.base_url%/nelmio/csp/reportContent-Typetext/html; charset=UTF-8DateTue, 07 Nov 2017 15:33:17 GMTKeep-Alivetimeout=5, max=58Referrer-Policyno-referrer, strict-origin-when-cross-originServerApache/2.4.23 (Win64) PHP/7.0.10X-Content-Security-Policyblock-all-mixed-content; font-src 'self' 'unsafe-inline' https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800 https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic https://use.fontawesome.com/4310d05301.js; img-src 'self' facebook.com flickr.com; script-src 'self' 'unsafe-inline' https://code.jquery.com/jquery-1.12.4.js https://code.jquery.com/ui/1.12.1/jquery-ui.js https://use.fontawesome.com/4310d05301.js https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js; style-src 'self' 'unsafe-inline' https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css https://resources/demos/style.css //netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css //netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css; report-uri router.request_context.base_url%/nelmio/csp/reportX-Content-Type-OptionsnosniffX-Frame-OptionsDENYX-Powered-ByPHP/7.0.10X-XSS-Protection1; mode=block

**Comment by samarhxc** [comment]
Did you solve your problem?

**Comment by chhoulet** [comment]
No, but a professionnal team is now in charge of the website.
Thank you very much for your support.
Christophe Houlet

      De : Simon Guionniere <notifications@github.com>
 À : froala/KMSFroalaEditorBundle <KMSFroalaEditorBundle@noreply.github.com> 
Cc : Houlet Christophe <chhoulet@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 5 décembre 2017 7h16
 Objet : Re: [froala/KMSFroalaEditorBundle] FroalaEditor doesn't show anything (#38)
   
Did you solve your problem?—
