### ISSUE TITLE
fontawesome

### ISSUE THREAD

**Issue by stickyhands** [froala/KMSFroalaEditorBundle#4]
fontawesome is missing in the bundle

{% if includeFontAwesome %}
    loadCSS( "{{ asset( basePath ~ "css/font-awesome.min.css" ) }}" );
{% endif %}

https://github.com/froala/KMSFroalaEditorBundle/tree/master/Resources/public/css

**Comment by samarhxc** [comment]
Thank you, 
Froala removed font-awesome from 1.7.
You can disable font awesome inclusion in the configuration, i

**Comment by samarhxc** [comment]
Froala removed Font Awesome in 1.7 version.
I'll fix that, you can disable Font Awesome inclusion from your configuration file.

**Comment by stefanneculai** [comment]
@samarhxc I believe the right way is to include it via composer. Like here: https://github.com/froala/wysiwyg-cake/blob/master/composer.json#L36

**Comment by samarhxc** [comment]
Normally fixed in last commit.
