### ISSUE TITLE
Events handling

### ISSUE THREAD

**Issue by martinopic** [froala/KMSFroalaEditorBundle#43]
Currently there is no way to handle events, it would be nice to have an additional options for the type: 

```php
$builder->add( "yourField", FroalaEditorType::class , 
    array('froalaEvents' => array('eventName' => 'functionName'))
```
I've already implemented this on an extension I made for a project but I think it would made a nice addition to the bundle, if you are interested I'd make a pull request.

**Comment by samarhxc** [comment]
You're right it's a good idea.
I can merge your PR or add this in the next update.
