### ISSUE TITLE
Incompatible jquery Version

### ISSUE THREAD

**Issue by amadohin** [froala/KMSFroalaEditorBundle#47]
Hi! I'm having a trouble with Froala Editor in Sonata Admin.

I'm using _datetime type_ and other fields, when I activate the Jquery inclusion in Froala config, the other fields don't work.

If I desactivate the jQuery inclusion the other fields work, but the froala type works unexpectedly

Here all is appearelly ok

![image](https://user-images.githubusercontent.com/27931966/35114262-c21da37a-fc49-11e7-95ce-21bf123e70d5.png)

 but when I clic inside the textarea, the toolbar changes

![image](https://user-images.githubusercontent.com/27931966/35114286-d9e2c080-fc49-11e7-9faa-c25737432389.png)

How can I fix this jQuery conflict?

**Comment by samarhxc** [comment]
Hi,
you have to include JQuery only one time.
I think the best solution is :
- desactivate the JQuery inclusion in Froala configuration
- update your JQuery version to (at least) 1.11
