### ISSUE TITLE
Upgrade help

### ISSUE THREAD

**Issue by jmsche** [froala/KMSFroalaEditorBundle#49]
Hi,

I'm wondering how I can help to upgrade the frontend files? Some upgrade process I can reproduce and then send some PR?

Something like this? :

* Remove `froala_editor_x.y.z` directory in `Resources/public`
* Add new files in `Resources/public/froala_editor_a.b.c`
* Update `$OPTIONS_STRING_CUSTOM::basePath` in `Utility/UConfiguration.php`

**Comment by samarhxc** [comment]
Hi, 
you have an option to change the base path if you want to use another Froala in your resources folder.

**Comment by jmsche** [comment]
My point is to help update this bundle, not only my project :)

**Comment by samarhxc** [comment]
What kind of improvements do you want to make ?
I think we have to keep the original Froala folder "froala_editor_x.y.z" to avoid version inconsistency.

**Comment by jmsche** [comment]
I'd just like to upgrade the original Froala which is included in this bundle

**Comment by samarhxc** [comment]
I planned to do this update today or tomorrow, it's a quick update but i need to add new options.

**Comment by samarhxc** [comment]
Update just pushed.
