### ISSUE TITLE
Froala initialization in form

### ISSUE THREAD

**Issue by stickyhands** [froala/KMSFroalaEditorBundle#5]
Hi,

in the file froala widget: https://github.com/froala/KMSFroalaEditorBundle/blob/master/Resources/views/Form/froala_widget.html.twig

You use $(document).ready to delay the execution of the JS till the page is fully loaded.
You should use something in vanilla js to prevent an error from the users that dont include jquery with froala and have their js block at the end of their template.

document.addEventListener("DOMContentLoaded", function() {
  // code...
});

or for IE8 and olders browsers:

document.attachEvent("onreadystatechange", function(){
  if (document.readyState === "complete"){
    document.detachEvent( "onreadystatechange", arguments.callee );
    // code ...
  }
});

**Comment by stefanneculai** [comment]
Froala Editor requires jQuery.

**Comment by stickyhands** [comment]
what if i do have JQuery but load it in a JS block at the bottom of my templates?

**Comment by stefanneculai** [comment]
jQuery must be included before the inclusion of the Froala Editor files.

**Comment by stickyhands** [comment]
> jQuery must be included before the inclusion of the Froala Editor files.
So to use the froala editor I have to follow a bad practice.

> The editor must be initialized after page load.
yep, but with $(document).ready you assume we all load Jquery in <head> or something.

imho, 2 solutions: 
dont use $(document).ready in the widget but rather use a vanilla js solution
or
remove the js code from the widget file and put it in his own .js file that we can load where we want and after Jquery (wherever it is)

**Comment by samarhxc** [comment]
This request is always up to date ?

**Comment by samarhxc** [comment]
JS can now be loaded manually by user.
