### ISSUE TITLE
Dependency Injection not working for the FormType (Symfony 4)

### ISSUE THREAD

**Issue by MaSt3r-iLLuSioN** [froala/KMSFroalaEditorBundle#50]
When trying to add this type as a field to my form it says that o arguments were passed and the constructor was expecting 4 in FroalaEditorType class. My Symfony version is 4. What are the exact steps to set this up with Symfony 4?
Thanks for your time.

**Comment by samarhxc** [comment]
Can you show your code ?

The following line is working on Sf4 👍 
`$form = $this->createFormBuilder( $data )->add( 'editor', FroalaEditorType::class, array(
				"language" => "fr",
			) )->getForm();`

**Comment by samarhxc** [comment]
Can you show some code ?

The folloing code is running on my Sf4 fresh install.
`
$data = array();
			$form = $this->createFormBuilder( $data )->add( 'editor', FroalaEditorType::class, array(
				"language" => "fr",
			) )->getForm();
`

**Comment by MaSt3r-iLLuSioN** [comment]
Sorry form my long delay in response, I have since sorted this out (misunderstanding on my end).
