### ISSUE TITLE
Array keys assumed to be unset are not checked before accessed

### ISSUE THREAD

**Issue by 01e9** [froala/KMSFroalaEditorBundle#55]
https://github.com/froala/KMSFroalaEditorBundle/blob/a6555e02d34481196b6cb9e1c458264b4290647c/Service/OptionManager.php#L125-L130

When I add in config:

```yaml
kms_froala_editor:
    imageManagerDeleteURL: null
```

I get

```
Notice: Undefined index: imageManagerDeleteURL
```

If I set `false`

```yaml
kms_froala_editor:
    imageManagerDeleteURL: false
```

it works because this check passes

https://github.com/froala/KMSFroalaEditorBundle/blob/a6555e02d34481196b6cb9e1c458264b4290647c/Service/OptionManager.php#L148

but you may change that check in future releases (for example strict null check `!== null`) and will break my project.

Please change the checks to something more explicit/clear, so we can understand what values are allowed.

For example that if can be changed to

```php
if( $imageManagerDeleteURL )
```

**Comment by mounikasure** [comment]
Verified 
![image](https://user-images.githubusercontent.com/47237466/56410911-835f6c80-629c-11e9-8a9e-17c5c36dae8f.png)
![image](https://user-images.githubusercontent.com/47237466/56410979-bbff4600-629c-11e9-9d9f-a3ac8dbec733.png)
