### ISSUE TITLE
Drop Symfony 2 support?

### ISSUE THREAD

**Issue by jmsche** [froala/KMSFroalaEditorBundle#61]
Hi,

I'm wondering if Symfony 2 support should be dropped or not, as maintaining it becomes harder and harder - especially if support is for 2.3+.

Eg. Symfony 4.1 throws deprecations for the routing controller format - should be `KMS\FroalaEditorBundle\Controller\MediaController::uploadImageAction` instead of `KMSFroalaEditorBundle:Media:uploadImage`.  
If I'm not wrong, this notation is available for 2.8 but not 2.3, so the fix would be hard to apply.

WDYT?

**Comment by jmsche** [comment]
Hi @sguionni, what do you think about this issue?

Could the bundle drop support for Symfony < 3 (or even < 4)?

**Comment by stefanneculai** [comment]
@jmsche @sguionni I believe we could make a separate branch for Symfony 2 / 3 and then continue with master on Symfony 4. What do you think?

**Comment by jmsche** [comment]
@stefanneculai I'm ok with that, but we should change the release process / tagging; IMO making a release for each Froala editor version is not great :/

What about creating a download command like FOSCKEditorBundle does? Seems to work well.

Also, we could list other stuff we'd want to do if we break the current release process. Eg. phpstan/phpcs integration?

**Comment by stefanneculai** [comment]
Looking for some input from @sguionni. Thanks in advance.

**Comment by sguionni** [comment]
Hi, 
i think we could split master into separate branch for each Symfony version.

But we need to change the  tagging method as you noticed.
Maybe something like this : 
2.2.9.1 for Froala 2.9.1 under Sf2,
3.2.9.0 for Froala 2.9.0 under Sf3 etc...

Actually i'm not using Symfony anymore, so my old project is still in Sf 2, i can maintain this version.

**Comment by jmsche** [comment]
If you're ok with this I'd be more in favor (at least for new releases that wouldn't support Symfony 2 anymore) for a download command, as described in my previous comment.

So new releases would bring new features, and developers wouldn't rely on a new release of this package to use the latest Froala Editor release :) 

An other issue with your tagging proposal is, introducing tags like `2.2.9.1` while `2.9.1` has already been released is somehow confusing, and I'm not even sure what I'd put in my composer.json file as a constraint to make it work :/

**Comment by stefanneculai** [comment]
I think we could actually make a separate branch for S2 and keep master branch for S3/S4. On the branch with S2, we can just rename the package to KMS2-FroalaEditorBundle and keep the same tagging as up to now.

I am good with the command, @jmsche. Do you think you could make a PR for it?

**Comment by jmsche** [comment]
I guess I could, but I'm going to need some time for that :) And for Symfony 4 deprecations removal as well.

Also I'd like your feedback (from both of you :)) about the following topics:

- phpstan integration
- phpcs integration
- adding tests

I guess the last point won't be an issue :D

**Comment by jmsche** [comment]
Added most of the changes (install command, Symfony 4.3+ support, Symfony 2/3 support removal...) into PR #89.

Opened issues #90 for docs update & #91 about code style/static analysis.
