### ISSUE TITLE
Image Manager - Any way to restrict to the owner only ?

### ISSUE THREAD

**Issue by adrienlamotte** [froala/KMSFroalaEditorBundle#65]
Hello !

The Image Manager plugin is pretty cool, but all users have acces to everyone uploads...
Can't really use that in production, because I use Froala in my admin area and in the front too for logged users.

Do you have any idea on how to restrict listing to user's only uploads ?

Thank you !

**Comment by sguionni** [comment]
Hello, 
the upload folder is configurable in your config file, or in the form builder.
You can specify a different one for each user by this second way.

**Comment by adrienlamotte** [comment]
Thank you @sguionni I didn't know it was configurable in the form builder !
It works great, just has to set a subfolder using the user ID.
