### ISSUE TITLE
How enable options useFrTag

### ISSUE THREAD

**Issue by ahonymous** [froala/KMSFroalaEditorBundle#7]
Hi!
How I can ow enable options useFrTag with this bundle. (https://www.froala.com/wysiwyg-editor/docs/options#useFrTag)

Thank's.

**Comment by samarhxc** [comment]
Hi, this option is not implemented yet, i will add it in the next commit.

**Comment by ahonymous** [comment]
Thank's. 
Can you add options to the paste formatting table with the all styles? (example: http://www.jqueryscript.net/demo/jQuery-WYSIWYG-Rich-Text-Editor-Plugin-Froala-Editor/)

**Comment by samarhxc** [comment]
Hi, sorry i was away during the entire month.
I'll add your options in the next release, for Froala 2 i think.

**Comment by samarhxc** [comment]
All Froala options are now supported.
Feel free to reopen this issue if something is wrong.
