### ISSUE TITLE
Error 1 : Bad link - Changing imageUploadFolder to /upload/anotherfolder

### ISSUE THREAD

**Issue by MauroCasula** [froala/KMSFroalaEditorBundle#8]
Hi there,

I just changed imageUploadFolder:

  ->add('content', 'froala', array(
                'mapped' => false,
                'data' => $this->data,
                'inlineMode' => false,
                "imageUploadFolder" => "/upload/cliente2"
            ));

And the editor give me an alert with the  message: Error 1 : Bad link.

Anyone know what can be this?

**Comment by MauroCasula** [comment]
Solved setting both imageUploadFolder and imageUploadPath.

You should update the docs. 

Thank you for this wonderful plugin!!!

**Comment by samarhxc** [comment]
Hi, 
i'm preparing a big update for the Froala v2 just released, 
the doc and configuration will totally change soon.
Thnx
