### ISSUE TITLE
Attempted to load class "Inflector" from namespace "Doctrine\Common\Util".

### ISSUE THREAD

**Issue by timoziemann** [froala/KMSFroalaEditorBundle#87]
Hi,

I have an issue on Symfony 4.2.8 and current dev-master with this line:
`$p_view->vars [ "arrOption" ][ "pluginsEnabled" ] = $this->m_pluginProvider->obtainArrPluginCamelized( $arrPlugin );`

![Bildschirmfoto 2019-05-17 um 13 43 24](https://user-images.githubusercontent.com/428303/57925863-f3680f00-78a9-11e9-9b18-29d2b523b330.png)

Occurs when rendering the form in a twig template. If I comment out the line, it's working fine. Adding the field to my form with this:

`$builder->add('text', FroalaEditorType::class, [
            'label' => 'Inhalt',
        ]);`

**Comment by jmsche** [comment]
@sguionni This is now fixed with v3 as doctrine/inflector is required in composer.json file

**Comment by sguionni** [comment]
Thanks!
